.sphinx/_static/github_issue_links.js
.sphinx/_templates/base.html
.sphinx/_templates/footer.html
.sphinx/_templates/header.html
custom_conf.py

This PR patches the documentation starter pack to support routing to Charmed HPC's GitHub Discussions from the documentation website. 
I enabled support for GitHub Discussions since we cannot use the Ubuntu Discourse as a support forum. We can use the forum for sending out announcements and information about Ubuntu HPC-related events, but it cannot be used as a support forum per its moderation policy.
* I updated the "Additional Resources" tab to route to our Matrix chat, GitHub organisation, and Discussions. I also included relevant links to the HPC pages on the Ubuntu website.
* I changed the `Give Feedback` button to say `Ask a question` because I think `Ask a question` is more inviting to Charmed HPC newcomers. Ideally, if folks are having issues with the documentation, we'll want to …

feat: update support links to route to Charmed HPC resources

---

howto/getting-started/index.md
howto/index.md

Small PR to add initial landing page for howto documentation, and a good exploration into how Sphinx renders nested categories. Next step after this is to add documentation for deploying the Slurm charms booth using the command-line and Juju bundles. We can use `sphinx-tabs` to switch between the Juju bundle and Juju CLI instructions.
Only thing I need to figure out is if we need to add any additional info for setting up the underlying cloud substrate of if that is something that needs to be saved for the tutorial or the Juju documentation itself

feat: add initial landing page for how-to and getting starts sections

---

.custom_wordlist.txt
.wordlist.txt
custom_conf.py
howto/getting-started/deploy-workload-manager.md
howto/getting-started/index.md

This PR adds the initial draft for how to deploy Slurm using both the Juju CLI and a bundle.
* Enabled sequential navigation within the doc site so that it is easier for readers to proceed through each howto as they walk through deploying their own Charmed HPC cluster.
* Moved HPC specific terms to `.custom_wordlist.txt` since `.wordlist.txt` is directly from the documentation starter pack and should remain unmodified.

feat: add how-to for deploying Slurm using both the CLI and a bundle

---

custom_conf.py
howto/getting-started/deploy-workload-manager.md
howto/getting-started/index.md
howto/index.md
howto/observability/connect-workload-manager-to-cos.md
howto/observability/index.md

This PR adds the how-to for connecting COS to Charmed HPC, the workload manager specifically. It is based primarily of off the internal documentation that we have for integrating COS and Slurm. I also added some revisions here and there where I thought some things could be more clear, and I made the `toctree` on the how-to index page hidden.
Future work will be adding a how-to for how to access the Grafana dashboard for the cluster.

feat: add how-to for connecting COS to Slurm (workload manager)

---

howto/getting-started/deploy-workload-manager.md
howto/getting-started/index.md
howto/index.md
howto/observability/access-grafana.md
howto/observability/connect-workload-manager-to-cos.md
howto/observability/index.md
index.md

This PR adds the how-to for accessing the Grafana dashboard after connecting the cluster workload manager to COS. 
The PR also updates some of the how-to titles to flow a bit better and be less terse, and updates the site navigation. I also made updates to documentation website landing page. The how-to card now includes links to the current how-to sections that we have.
I also added a warning admonition to the landing page about how Charmed HPC is in _pre-alpha_. The purpose for adding this admonition is that we're still stabilizing some bits with the exporter (we need a Debian package for it) and the COS enabled Slurm charms haven't been rolled into stable yet. It would be good to include a "buyer beware" message, but also invite folks to help by testing things out as early adopters.

feat: add how-to for accessing Grafana dashboard

---

.custom_wordlist.txt
explanation/cryptography/index.md
explanation/cryptography/jwt.md
explanation/cryptography/munge.md
explanation/index.md

Documents all our current key generation algorithms.

feat: introduce cryptographic documentation

---

howto/getting-started/deploy-workload-manager.md

This PR fixes the bundle for deploying the workload manager. As is, the deployment fails on Juju 3.x because Juju tries to find the charms in the `stable` channel ([proof](https://app.warp.dev/block/4M10A506n5YtI57oyQ0uTI)).
Also, in case the channel is fixed, all application will get `unkown` state because there's no unit set for any of them. This PR fixes this behaviour as well by adding the key `num_units` to all applications but `slurmdbd-mysql-router`.

Correct the bundle in the *deploy-workload-manager.md* file

---

.custom_wordlist.txt
explanation/gpus/driver.md
explanation/gpus/index.md
explanation/gpus/slurmconf.md
explanation/index.md
reference/gres/index.md
reference/index.md

Adds sections to Explanation for the GPU support recently merged into the Slurm charms. Once we have Reference docs, we'll likely want to update these sections to include links to at least a table of supported GPU models.
I've gone with `Driver auto-install` and `Slurm enlistment` as subsection titles but wonder if these should be `GPU driver auto-install` and `Slurm enlistment of GPUs`. This would make the context obvious when, e.g., looking through search results, however would mean a lot of repetition of "GPU". Let me know your thoughts.

docs: add initial GPU explanation

---

.sphinx/_templates/header.html

`Source Code` is a misnomer since it doesn't navigate the reader to the full source code of Charmed HPC; it just takes you to a collection of a couple of repositories. `GitHub Organization` is better since it helps folks get connected with the project on GitHub, not necessarily dump them in a hodgepodge of repositories.

feat(header): rename `Source Code` to `GitHub Organization`

---

custom_conf.py
howto/getting-started/deploy-slurm.md

This change is necessary as it greatly improves tabbed content visually when in dark mode. White text no longer looks sad and sandwiched right up against the dark gray box when it is inside the tab container.

fix: replace `sphinx_tabs` with MyST tabs

---

CONTRIBUTING.md
README.md
explanation/index.md
howto/index.md
index.md
tutorial/first-steps.md

Updated the landing page descriptions for how-to and explanation, removed empty tutorial page for time being, updated homepage to reflect new content, and made some minor edits to the README and Contributing docs.

docs: Updates to landing pages and minor edits

---

.custom_wordlist.txt
explanation/index.md
explanation/interconnects/driver.md
explanation/interconnects/index.md
reference/index.md
reference/interconnects/index.md

Adds an explanation for high-speed interconnects/RDMA implementations, including general definitions and how Charmed-HPC enables RDMA use.
Adds a reference table for cloud interconnects and their status in Charmed-HPC. At the moment, Azure is the only supported cloud out of the box but I've also included some AWS details following investigative work into their EFA solution.

docs(rdma): initial interconnects Explanation and Reference sections

---

.custom_wordlist.txt
howto/getting-started/deploy-shared-filesystem.md
howto/getting-started/deploy-slurm.md
howto/getting-started/index.md
howto/getting-started/initialize-cloud-environment.md
howto/index.md
howto/observability/connect-slurm-to-cos.md

Like PR title says, this PR adds a how-to for initializing the cloud environment which we will deploy Charmed HPC in. Currently I just started off with LXD and Canonical Kubernetes since I want to get the structure of the page correct, but ideally we'll be able to expand it as we start to bring on more clouds such as Azure and AWS.
* Resolves #20 
* Removed extraneous whitespace.
* Linked "Deploy Slurm" how-to to "Initialize cloud environment" how-to.
* Updated "Deploy Slurm" how-to to include info about deploying Slurm to the created machine cloud `charmed-hpc`
* In the Identity how-to I will be deploying the Identity charms like glauth-k8s to the Kubernetes cloud `charmed-hpc-k8s`
* I further granularized the reference links we've created to reduce the chances of name clashes between …

feat: add how-to for initializing cloud environment of Charmed HPC

---

reference/underlying-projects-and-dependencies.md

https://github.com/canonical/charm-relation-interfaces/pull/217 was merged, so we can add the interface to our list of maintained projects and dependencies.

feat: add filesystem_info to the reference

---

.custom_wordlist.txt
howto/index.md
howto/setup/enable-job-profiling-with-influxdb.md
howto/setup/index.md

Short howto on enabling job profiling with influxdb.
Depends on https://github.com/charmed-hpc/slurm-charms/pull/70

Enable job profiling with influxdb

---

howto/manage/integrate-with-cos.md

A minor fix to the COS integration instructions to include ` --base "ubuntu@24.04"` when deploying `grafana-agent`. If this is not included, the charm is deployed with `ubuntu@22.04` and gives a "bases must match" error when trying to integrate it with the `ubuntu@24.04` Slurm charms.

fix: add `--base` to `grafana-agent` deploy command

---

howto/setup/deploy-glauth.md

Fixes a small bug on the documentation related to deploying `sssd`, since it requires specifying the base to be compatible with the deployed slurmd and sackd nodes.

fix: add base when deploying sssd

---

reference/monitoring/index.md
reference/monitoring/loki.md

~Depends on #57.~
Adds reference documentation for the exported Loki logs on each charm.

feat: add reference documentation for loki

---

reference/monitoring/loki.md

Adds entries in our Loki docs for how to fetch the logs of slurmd and slurmdbd, in preparation of https://github.com/charmed-hpc/slurm-charms/pull/98.

feat: add Loki docs for the rest of the Slurm charms

---

howto/setup/deploy-shared-filesystem.md

[//]: # (Please summarize your commits here. For any complex or contenious changes, please also provide justifications.)
Update the shell commands in the filesystem howto to be correct. We must specify `--channel latest/edge` since by default Juju will only pull from `latest/stable`. Also `--config` is required for every configuration option you want to set at deploy as `--config` does not accept a variable amount of arguments from the command line.
Other changes:
- Reformat shell commands to follow styling convention of the rest of the documentation. 2 space indents for shell commands.
[//]: # (Please link to related issues, pull requests, and discussions here - especially corresponding code PRs. If your PR has no related issues, PRs, or discussions, please provide a justification for …

fix: use correct `juju` commands for deploying filesystem proxies

---

index.md

[//]: # (Please summarize your commits here. For any complex or contentious changes, please also provide justifications.)
Updates the home page Project and community section to include links for the newly created org-level CONTRIBUTING.md guide and README.md. Also tweaks some wording in the other links to make the flow more consistent. 
[//]: # (Please link to related issues, pull requests, and discussions here - especially corresponding code PRs. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
[Pull Request to add org-level README - merged](https://github.com/charmed-hpc/.github/pull/22)
[Pull Request to add org-level CONTRIBUTING.md guide - merged](https://github.com/charmed-hpc/.github/pull/19)

Update home page governance links

---

.custom_wordlist.txt
howto/setup/deploy-shared-filesystem.md
reference/underlying-projects-and-dependencies.md

[//]: # (Please summarize your commits here. For any complex or contentious changes, please also provide justifications.)
This PR fixes the failing link checks that are causing our CI to wig out. In the end, we had two culprits causing the issue:
1. Some of the problematic links pointed to sections in the Juju documentation that no longer exist. I fixed them by hunting down the new sections in the Juju docs.
2. We had some links pointing to the old Slurm interface implementations. I've updated them to point to the new interface implementations in `hpc-libs`. Eventually I want us to have dedicated dev docs/a README that explains how to use the interfaces, but _I think_ we also want to evaluate moving the Slurm interfaces to a new location, so we'll cross that bridge when we get there …

fix: correct busted link checks

---

.custom_wordlist.txt
howto/index.md
howto/manage/index.md
howto/manage/integrate-with-apptainer.md
howto/use/index.md
howto/use/use-apptainer.md

[//]: # (Please summarize your commits here. For any complex or contentious changes, please also provide justifications.)
This PR adds two new documentations pages:
1. Integrate with Apptainer
2. Use Apptainer
The "Integrate with Apptainer" how-to focuses on integrating Apptainer with the Slurm charms after they have been deployed, and the "Use Apptainer" how-to focuses on the different ways that a user can leverage Apptainer within Charmed HPC such as building custom images or running workloads.
1. There's currently a commented out section in the "Use Apptainer" how-to because it's related to bug https://github.com/charmed-hpc/slurm-charms/issues/143. Once I fix this bug, I'll uncomment this part of the how-to because it's quite useful.
2. Eventually, we might also want a "Manage …

feat: add Apptainer how-tos
